name: Go

on:
  push:
    branches-ignore:
    # Version 1.0 does not work with the "go" tool properly.
    - "1.0"
  pull_request:
    branches-ignore:
    # Version 1.0 does not work with the "go" tool properly.
    - "1.0"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build go
      run: go build -mod=mod -v ./...
      working-directory: ./go

    - name: Test go
      run: go test -mod=mod -v ./...
      working-directory: ./go

    - name: Build examples/go
      run: go build -mod=mod -v ./...
      working-directory: ./examples/go

    - name: Build privacy-on-beam
      run: go build -mod=mod -v ./...
      working-directory: ./privacy-on-beam

    - name: Test privacy-on-beam
      run: go test -mod=mod -v ./...
      working-directory: ./privacy-on-beam
